// AUTO-GENERATED by design-inventor
// Company: Unique Air Duct (Air Duct Cleaning — California)
// Creative direction: Illustrated air-quality storybook — tilted cream ribbon banners carry heavy-condensed headlines over a deep-magenta-to-plum hero, with lime-green airflow swooshes drifting across sections; alternating cream/lavender/deep-magenta rhythm paced by HashiCorp-style uppercase wayfinding labels and Binance-inspired 50px pill CTAs with spring-overshoot hovers.
// Logo-anchored: YES (primary hue 294 = magenta banner; secondary hue 124 = airflow green)

export const designConfig = {
  colors: {
    primary: '#B41FCF',
    primaryLight: '#F3E3F6',
    primaryDark: '#63176F',
    secondary: '#35C451',
    accent: '#FFCF2A',
    background: '#FDF9F5',
    surface: '#F6EDF7',
    surfaceDark: '#1D0B24',
    textPrimary: '#1B0920',
    textSecondary: '#5A4861',
    textLight: '#9E8AA5',
    border: '#E7D9E9',
  },

  fonts: {
    display: 'Barlow Condensed',
    body: 'Nunito',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@700;800;900&family=Nunito:wght@400;500;600;700;800&display=swap',
    headingWeight: 'font-extrabold',
    headingTracking: '-0.01em',
    headingLineHeight: '1.05',
    labelsUppercase: true,
  },

  hero: {
    pattern: 'tilted-ribbon-banner-hero',
    backgroundType: 'gradient-mesh',
    contentAlignment: 'center',
    ctaShape: 'pill',
    hasStats: true,
  },

  services: {
    pattern: 'bento-grid',
    requiresClientComponent: true,
    cardImageAspect: '16:10',
    sectionBg: 'surface',
    headerAlignment: 'left',
  },

  colorMood: {
    dominantTone: 'vibrant',
  },

  style: {
    name: 'ribbon-magenta-airflow',
    headerType: 'floating-pill',
    hasMegaMenu: false,
    hasTopBar: false,
    mobileStyle: 'slide-in-right-overlay',

    // Richness flags (11 active, well above the 5 minimum)
    hasScrollProgress: true,
    hasParallax: true,
    hasFloatingBlobs: true,
    hasTiltCards: false,
    hasMagneticButtons: true,
    hasSplitText: true,
    hasPinnedSteps: false,
    hasCursorFollower: true,
    hasGsapScrollTrigger: true,
    hasLenisScroll: true,
    hasParticleHero: false,
    hasSwiperCarousel: true,
    hasVanillaTilt: false,
    hasGsapTextReveal: true,
    hasScrollScrub: true,
    hasCursorSpotlight: false,
    hasRippleClick: true,

    counterStyle: 'spring-overshoot',
    hasImageMarquee: false,
    hasProjectGallery: false,
    hasSlideshowHero: false,
    hasBeforeAfter: true,
    hasPolaroidGallery: false,
    hasHoverReveal: false,
    hasHorizontalTheater: false,
    textDensity: 'standard',
  },

  sectionOrder: [
    'Hero',
    'StatsBar',
    'Services',
    'BeforeAfter',
    'ProcessSteps',
    'WhyUs',
    'Testimonials',
    'FAQ',
    'Areas',
    'CTA',
  ],

  sections: {
    stats: {
      bg: '#FDF9F5',
      textColor: '#1B0920',
      numberColor: '#B41FCF',
    },
    testimonials: {
      style: 'conversation-bubbles',
      bg: '#F6EDF7',
    },
    cta: {
      bg: '#1D0B24',
      hasBackgroundImage: false,
    },
  },
} as const;

export type DesignConfig = typeof designConfig;
